scss_files: 'test/fixtures/scss/*.scss'

linters:
  Indentation:
    enabled: true
    width: 2
  DuplicateProperty:
    enabled: true
    severity: error
  EmptyRule:
    enabled: true
    severity: error
